import { useMemo } from "react";
import { geoOrthographic, geoPath } from "d3-geo";
import { feature } from "topojson-client";
// Simplified copy of world-atlas's country data, generated by
// scripts/build-globe-data.mjs.
import countries110m from "../data/globe-countries.json";

const SIZE = 340;

// Fixed orientation, no rotation — centered on the Asia/Africa side of
// the world, where most of the talent network is based.
const CENTER = { lon: 80, lat: 15 };

// A static d3-geo orthographic-projection globe, fixed to face
// Asia/Africa. Purely decorative (aria-hidden) — it no longer marks
// specific countries.
export default function Globe({ className }) {
  const projection = useMemo(() => {
    const p = geoOrthographic().clipAngle(90).rotate([-CENTER.lon, -CENTER.lat]);
    p.fitExtent(
      [
        [16, 16],
        [SIZE - 16, SIZE - 16],
      ],
      { type: "Sphere" }
    );
    return p;
  }, []);

  const countries = useMemo(
    () => feature(countries110m, countries110m.objects.countries).features,
    []
  );

  const { landPath, outlinePath } = useMemo(() => {
    const path = geoPath(projection);
    return {
      landPath: countries.map((c) => path(c)).filter(Boolean).join(" "),
      outlinePath: path({ type: "Sphere" }),
    };
  }, [projection, countries]);

  return (
    <svg className={className} viewBox={`0 0 ${SIZE} ${SIZE}`} aria-hidden="true">
      <defs>
        {/* Light-themed sphere — the ocean (this gradient) is a light
            grey, land (.map-land below) is white. */}
        <radialGradient id="globeGradient" cx="35%" cy="30%" r="75%">
          <stop offset="0%" stopColor="#eceff4" />
          <stop offset="55%" stopColor="#d8dde6" />
          <stop offset="100%" stopColor="#c2cad6" />
        </radialGradient>
      </defs>
      {/* Solid base matching the gradient's own mid tone, as a fallback
          backing so the sphere is guaranteed opaque regardless of the
          gradient rendering. */}
      <path d={outlinePath} fill="#d8dde6" />
      <path d={outlinePath} fill="url(#globeGradient)" />
      <path d={landPath} className="map-land" />
      <path d={outlinePath} className="globe-outline" />
    </svg>
  );
}
